/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { EventTickets } from './EventTickets.js';
export * as factories from './factories/index.js';
export { EventTickets__factory } from './factories/EventTickets__factory.js';