export const CURRENCY = 'USD'

export const events = [
  {
    id: 'evt_aurora',
    slug: 'aurora-nights-world-tour',
    title: 'Aurora Nights — World Tour',
    category: 'Concert',
    image: '/events/concert.png',
    venue: 'Skyline Arena',
    city: 'New York, NY',
    date: 'Sat, Oct 18, 2026',
    time: '8:00 PM',
    organizer: 'LiveNation Collective',
    organizerVerified: true,
    priceFrom: 89,
    trending: true,
    soldPct: 82,
    chain: 'Base',
    description:
      'The Aurora Nights World Tour lands in New York for one unforgettable evening of light, sound, and spectacle. Every ticket is minted on-chain, guaranteeing authenticity and effortless resale.',
    lineup: ['Aurora', 'Neon Bloom', 'The Midnight Echo'],
    tiers: [
      {
        id: 'ga',
        name: 'General Admission',
        price: 89,
        fee: 6,
        perks: ['Standing floor access', 'On-chain e-ticket'],
        remaining: 240,
        total: 1200,
      },
      {
        id: 'lower',
        name: 'Lower Bowl Reserved',
        price: 149,
        fee: 9,
        perks: ['Reserved seat', 'Priority entry', 'On-chain e-ticket'],
        remaining: 86,
        total: 800,
      },
      {
        id: 'vip',
        name: 'VIP Front Stage',
        price: 329,
        fee: 18,
        perks: ['Front rows', 'Lounge access', 'Collectible NFT stub', 'Merch bundle'],
        remaining: 12,
        total: 120,
      },
    ],
  },
  {
    id: 'evt_solstice',
    slug: 'solstice-music-festival',
    title: 'Solstice Music Festival',
    category: 'Festival',
    image: '/events/festival.png',
    venue: 'Riverside Grounds',
    city: 'Austin, TX',
    date: 'Fri, Jul 10, 2026',
    time: '2:00 PM',
    organizer: 'Solstice Presents',
    organizerVerified: true,
    priceFrom: 175,
    trending: true,
    soldPct: 64,
    chain: 'Base',
    description:
      'Three days, five stages, and a lineup that defines the summer. Solstice returns with fully transferable on-chain passes so plans can change without the panic.',
    lineup: ['Kaskade', 'Rufus Du Sol', 'ODESZA', 'Jamie xx'],
    tiers: [
      {
        id: 'day',
        name: 'Single Day Pass',
        price: 175,
        fee: 11,
        perks: ['One-day access', 'On-chain e-ticket'],
        remaining: 520,
        total: 3000,
      },
      {
        id: 'weekend',
        name: 'Weekend Pass',
        price: 389,
        fee: 22,
        perks: ['All 3 days', 'Re-entry', 'On-chain e-ticket'],
        remaining: 140,
        total: 2000,
      },
      {
        id: 'vip',
        name: 'VIP Weekend',
        price: 749,
        fee: 39,
        perks: ['Viewing decks', 'Premium bars', 'Fast lane', 'Collectible NFT'],
        remaining: 28,
        total: 400,
      },
    ],
  },
  {
    id: 'evt_chainconf',
    slug: 'chainconf-2026',
    title: 'ChainConf 2026',
    category: 'Conference',
    image: '/events/conference.png',
    venue: 'Metro Convention Center',
    city: 'San Francisco, CA',
    date: 'Wed, Sep 9, 2026',
    time: '9:00 AM',
    organizer: 'ChainConf Foundation',
    organizerVerified: true,
    priceFrom: 299,
    trending: false,
    soldPct: 47,
    chain: 'Optimism',
    description:
      'The premier gathering for builders shaping the on-chain future. Two days of keynotes, workshops, and networking with credentials verifiable on-chain.',
    lineup: ['120+ Speakers', '40 Workshops', 'Demo Arena'],
    tiers: [
      {
        id: 'std',
        name: 'Standard Pass',
        price: 299,
        fee: 15,
        perks: ['All keynotes', 'Expo hall', 'On-chain badge'],
        remaining: 610,
        total: 1500,
      },
      {
        id: 'pro',
        name: 'Pro Pass',
        price: 549,
        fee: 27,
        perks: ['Workshops', 'Speaker lounge', 'Recordings', 'On-chain badge'],
        remaining: 190,
        total: 600,
      },
    ],
  },
  {
    id: 'evt_finals',
    slug: 'city-finals-game-7',
    title: 'City Finals — Game 7',
    category: 'Sports',
    image: '/events/sports.png',
    venue: 'Downtown Fieldhouse',
    city: 'Chicago, IL',
    date: 'Sun, Jun 21, 2026',
    time: '6:30 PM',
    organizer: 'Metro Sports Group',
    organizerVerified: true,
    priceFrom: 120,
    trending: true,
    soldPct: 95,
    chain: 'Base',
    description:
      'Winner takes all. The decisive Game 7 of the City Finals, with anti-scalper on-chain tickets and price-capped resale to keep it fair for real fans.',
    lineup: ['Center Court', 'Baseline', 'Club Level'],
    tiers: [
      {
        id: 'upper',
        name: 'Upper Deck',
        price: 120,
        fee: 8,
        perks: ['Assigned seat', 'On-chain e-ticket'],
        remaining: 60,
        total: 2500,
      },
      {
        id: 'club',
        name: 'Club Level',
        price: 285,
        fee: 16,
        perks: ['Padded seat', 'Club lounge', 'On-chain e-ticket'],
        remaining: 24,
        total: 900,
      },
      {
        id: 'court',
        name: 'Courtside',
        price: 890,
        fee: 44,
        perks: ['Courtside seat', 'VIP entrance', 'Collectible NFT'],
        remaining: 4,
        total: 40,
      },
    ],
  },
  {
    id: 'evt_lastlaugh',
    slug: 'the-last-laugh-live',
    title: 'The Last Laugh — Live',
    category: 'Comedy',
    image: '/events/comedy.png',
    venue: 'The Basement Club',
    city: 'Los Angeles, CA',
    date: 'Thu, Aug 6, 2026',
    time: '9:30 PM',
    organizer: 'Basement Nights',
    organizerVerified: false,
    priceFrom: 45,
    trending: false,
    soldPct: 38,
    chain: 'Base',
    description:
      'An intimate late-night set from the sharpest names in stand-up. Limited seats, big laughs, and tickets you actually own.',
    lineup: ['Headliner: Dana Cross', 'Guest: Marco Reyes'],
    tiers: [
      {
        id: 'ga',
        name: 'General Seating',
        price: 45,
        fee: 4,
        perks: ['Open seating', 'On-chain e-ticket'],
        remaining: 90,
        total: 160,
      },
      {
        id: 'front',
        name: 'Front Table',
        price: 95,
        fee: 7,
        perks: ['Reserved table', '2 drinks', 'On-chain e-ticket'],
        remaining: 14,
        total: 40,
      },
    ],
  },
  {
    id: 'evt_symphony',
    slug: 'moonlight-symphony-gala',
    title: 'Moonlight Symphony Gala',
    category: 'Theater',
    image: '/events/theater.png',
    venue: 'Grand Opera House',
    city: 'Boston, MA',
    date: 'Sat, Dec 12, 2026',
    time: '7:30 PM',
    organizer: 'Metropolitan Arts',
    organizerVerified: true,
    priceFrom: 110,
    trending: false,
    soldPct: 55,
    chain: 'Optimism',
    description:
      'A black-tie evening of orchestral masterworks beneath the chandeliers of the Grand Opera House. Elegant, timeless, and fully on-chain.',
    lineup: ['Metropolitan Orchestra', 'Conductor: Lena Vasquez'],
    tiers: [
      {
        id: 'balcony',
        name: 'Balcony',
        price: 110,
        fee: 8,
        perks: ['Balcony seat', 'On-chain e-ticket'],
        remaining: 210,
        total: 600,
      },
      {
        id: 'orchestra',
        name: 'Orchestra',
        price: 240,
        fee: 14,
        perks: ['Prime seat', 'Program', 'On-chain e-ticket'],
        remaining: 70,
        total: 400,
      },
      {
        id: 'box',
        name: 'Private Box',
        price: 620,
        fee: 32,
        perks: ['Private box', 'Champagne service', 'Collectible NFT'],
        remaining: 6,
        total: 20,
      },
    ],
  },
  {
    id: 'evt_pulse',
    slug: 'pulse-warehouse-rave',
    title: 'Pulse — Warehouse Rave',
    category: 'Electronic',
    image: '/events/electronic.png',
    venue: 'Dock 9 Warehouse',
    city: 'Miami, FL',
    date: 'Sat, Nov 7, 2026',
    time: '10:00 PM',
    organizer: 'Pulse Collective',
    organizerVerified: true,
    priceFrom: 65,
    trending: true,
    soldPct: 71,
    chain: 'Base',
    description:
      'A night of pure sound design in a raw industrial space. On-chain wristbands mean no wristband cutting, no fakes — just the music.',
    lineup: ['Amelie Lens', 'Sara Landry', 'I Hate Models'],
    tiers: [
      {
        id: 'ga',
        name: 'General Admission',
        price: 65,
        fee: 5,
        perks: ['Full night access', 'On-chain wristband'],
        remaining: 300,
        total: 1400,
      },
      {
        id: 'vip',
        name: 'VIP Riser',
        price: 165,
        fee: 10,
        perks: ['Elevated riser', 'Fast entry', 'Coat check', 'Collectible NFT'],
        remaining: 40,
        total: 200,
      },
    ],
  },
]

export function getEvent(slug) {
  return events.find((e) => e.slug === slug)
}

export const categories = [
  'Concert',
  'Festival',
  'Conference',
  'Sports',
  'Comedy',
  'Theater',
  'Electronic',
]

export const myTickets = [
  {
    id: 't1',
    ticketId: '#TCK-4821',
    eventSlug: 'aurora-nights-world-tour',
    eventTitle: 'Aurora Nights — World Tour',
    category: 'Concert',
    image: '/events/concert.png',
    venue: 'Skyline Arena',
    city: 'New York, NY',
    date: 'Sat, Oct 18, 2026',
    time: '8:00 PM',
    tier: 'VIP Front Stage',
    seat: 'Sec A · Row 2 · Seat 14',
    status: 'Valid',
    txHash: '0x7a3f…c21e',
    owner: '0x9f2b…7d4a',
    qrToken: 'AURORA-4821-9F2B-7D4A',
  },
  {
    id: 't2',
    ticketId: '#TCK-3390',
    eventSlug: 'pulse-warehouse-rave',
    eventTitle: 'Pulse — Warehouse Rave',
    category: 'Electronic',
    image: '/events/electronic.png',
    venue: 'Dock 9 Warehouse',
    city: 'Miami, FL',
    date: 'Sat, Nov 7, 2026',
    time: '10:00 PM',
    tier: 'VIP Riser',
    seat: 'GA · Riser Access',
    status: 'Valid',
    txHash: '0x2c88…a19f',
    owner: '0x9f2b…7d4a',
    qrToken: 'PULSE-3390-9F2B-7D4A',
  },
  {
    id: 't3',
    ticketId: '#TCK-1157',
    eventSlug: 'chainconf-2026',
    eventTitle: 'ChainConf 2026',
    category: 'Conference',
    image: '/events/conference.png',
    venue: 'Metro Convention Center',
    city: 'San Francisco, CA',
    date: 'Wed, Sep 9, 2026',
    time: '9:00 AM',
    tier: 'Pro Pass',
    seat: 'Badge · All Access',
    status: 'Listed',
    txHash: '0x5be1…04cd',
    owner: '0x9f2b…7d4a',
    qrToken: 'CHAIN-1157-9F2B-7D4A',
  },
  {
    id: 't4',
    ticketId: '#TCK-0042',
    eventSlug: 'solstice-music-festival',
    eventTitle: 'Solstice Music Festival',
    category: 'Festival',
    image: '/events/festival.png',
    venue: 'Riverside Grounds',
    city: 'Austin, TX',
    date: 'Fri, Jul 10, 2026',
    time: '2:00 PM',
    tier: 'Weekend Pass',
    seat: 'GA · Weekend',
    status: 'Used',
    txHash: '0x1def…88ac',
    owner: '0x9f2b…7d4a',
    qrToken: 'SOLST-0042-9F2B-7D4A',
  },
]

export const resaleListings = [
  {
    id: 'r1',
    eventTitle: 'City Finals — Game 7',
    eventSlug: 'city-finals-game-7',
    category: 'Sports',
    image: '/events/sports.png',
    city: 'Chicago, IL',
    date: 'Sun, Jun 21, 2026',
    tier: 'Club Level',
    seat: 'Sec 112 · Row F',
    facePrice: 285,
    listPrice: 310,
    priceCap: 342,
    seller: '0x4a1c…9b2e',
    verified: true,
  },
  {
    id: 'r2',
    eventTitle: 'Solstice Music Festival',
    eventSlug: 'solstice-music-festival',
    category: 'Festival',
    image: '/events/festival.png',
    city: 'Austin, TX',
    date: 'Fri, Jul 10, 2026',
    tier: 'Weekend Pass',
    seat: 'GA · Weekend',
    facePrice: 389,
    listPrice: 380,
    priceCap: 467,
    seller: '0x77de…10ff',
    verified: true,
  },
  {
    id: 'r3',
    eventTitle: 'Aurora Nights — World Tour',
    eventSlug: 'aurora-nights-world-tour',
    category: 'Concert',
    image: '/events/concert.png',
    city: 'New York, NY',
    date: 'Sat, Oct 18, 2026',
    tier: 'Lower Bowl Reserved',
    seat: 'Sec 108 · Row M',
    facePrice: 149,
    listPrice: 165,
    priceCap: 179,
    seller: '0x2b90…44a1',
    verified: false,
  },
  {
    id: 'r4',
    eventTitle: 'Pulse — Warehouse Rave',
    eventSlug: 'pulse-warehouse-rave',
    category: 'Electronic',
    image: '/events/electronic.png',
    city: 'Miami, FL',
    date: 'Sat, Nov 7, 2026',
    tier: 'General Admission',
    seat: 'GA',
    facePrice: 65,
    listPrice: 70,
    priceCap: 78,
    seller: '0x9c3a…2f5b',
    verified: true,
  },
]

export const transactions = [
  {
    id: 'tx1',
    type: 'Purchase',
    event: 'Aurora Nights — World Tour',
    date: 'May 2, 2026 · 14:22',
    amount: 347,
    direction: 'out',
    status: 'Confirmed',
    txHash: '0x7a3f9b2c4d5e6f7a8b9c0d1e2f3a4b5c21e',
  },
  {
    id: 'tx2',
    type: 'Purchase',
    event: 'Pulse — Warehouse Rave',
    date: 'Apr 28, 2026 · 09:10',
    amount: 175,
    direction: 'out',
    status: 'Confirmed',
    txHash: '0x2c88a19f0b1c2d3e4f5a6b7c8d9e0f1a19f',
  },
  {
    id: 'tx3',
    type: 'Resale',
    event: 'ChainConf 2026 · Pro Pass',
    date: 'Apr 20, 2026 · 18:47',
    amount: 540,
    direction: 'in',
    status: 'Pending',
    txHash: '0x5be104cda1b2c3d4e5f6a7b8c9d0e1f204cd',
  },
  {
    id: 'tx4',
    type: 'Transfer',
    event: 'Solstice Music Festival · GA',
    date: 'Apr 11, 2026 · 12:03',
    amount: 0,
    direction: 'out',
    status: 'Confirmed',
    txHash: '0x1def88aca2b3c4d5e6f7a8b9c0d1e2f388ac',
  },
  {
    id: 'tx5',
    type: 'Purchase',
    event: 'Solstice Music Festival · Weekend',
    date: 'Mar 30, 2026 · 21:15',
    amount: 411,
    direction: 'out',
    status: 'Confirmed',
    txHash: '0x9aa1b2c3d4e5f6a7b8c9d0e1f2a3b4c5d6e7',
  },
]

export const organizerEvents = [
  {
    id: 'oe1',
    title: 'Aurora Nights — World Tour',
    slug: 'aurora-nights-world-tour',
    date: 'Oct 18, 2026',
    city: 'New York, NY',
    image: '/events/concert.png',
    status: 'On sale',
    sold: 1746,
    capacity: 2120,
    gross: 214980,
  },
  {
    id: 'oe2',
    title: 'Pulse — Warehouse Rave',
    slug: 'pulse-warehouse-rave',
    date: 'Nov 7, 2026',
    city: 'Miami, FL',
    image: '/events/electronic.png',
    status: 'On sale',
    sold: 1136,
    capacity: 1600,
    gross: 98420,
  },
  {
    id: 'oe3',
    title: 'City Finals — Game 7',
    slug: 'city-finals-game-7',
    date: 'Jun 21, 2026',
    city: 'Chicago, IL',
    image: '/events/sports.png',
    status: 'Sold out',
    sold: 3440,
    capacity: 3440,
    gross: 612300,
  },
  {
    id: 'oe4',
    title: 'Winter Loft Sessions',
    slug: 'winter-loft-sessions',
    date: 'Jan 24, 2027',
    city: 'Seattle, WA',
    image: '/events/comedy.png',
    status: 'Draft',
    sold: 0,
    capacity: 300,
    gross: 0,
  },
]

export const salesByMonth = [
  { month: 'Jan', revenue: 42000 },
  { month: 'Feb', revenue: 58000 },
  { month: 'Mar', revenue: 51000 },
  { month: 'Apr', revenue: 79000 },
  { month: 'May', revenue: 96000 },
  { month: 'Jun', revenue: 134000 },
]

export const attendees = [
  {
    id: 'a1',
    wallet: '0x9f2b…7d4a',
    event: 'Aurora Nights',
    tier: 'VIP Front Stage',
    purchased: 'May 2',
    status: 'Valid',
  },
  {
    id: 'a2',
    wallet: '0x4a1c…9b2e',
    event: 'Aurora Nights',
    tier: 'Lower Bowl',
    purchased: 'May 1',
    status: 'Checked in',
  },
  {
    id: 'a3',
    wallet: '0x77de…10ff',
    event: 'Pulse Rave',
    tier: 'VIP Riser',
    purchased: 'Apr 28',
    status: 'Valid',
  },
  {
    id: 'a4',
    wallet: '0x2b90…44a1',
    event: 'Aurora Nights',
    tier: 'General Admission',
    purchased: 'Apr 26',
    status: 'Resold',
  },
  {
    id: 'a5',
    wallet: '0x9c3a…2f5b',
    event: 'Pulse Rave',
    tier: 'General Admission',
    purchased: 'Apr 24',
    status: 'Checked in',
  },
]

export function formatUsd(n) {
  return new Intl.NumberFormat('en-US', {
    style: 'currency',
    currency: 'USD',
    maximumFractionDigits: 0,
  }).format(n)
}